In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
#data_dir='/content/drive/MyDrive/Colab_Notebooks/Ebay/data/'
data_dir = '/Users/pamelakatali/Downloads/Ebay_ML/data/'

In [3]:
train_df = pd.read_csv(data_dir+'clean_ebay_train.tsv.gz', sep='\t')
train_df.head()

Unnamed: 0  declared_handling_days  carrier_min_estimate  \
0           0                     1.0                     2   
1           1                     2.0                     2   
2           2                     3.0                     2   
3           3                     1.0                     3   
4           4                     1.0                     3   

   carrier_max_estimate  carrier_diff_estimate  accept_days  shipping_dist  \
0                     5                      3            0    1102.615869   
1                     5                      3            1     454.104441   
2                     5                      3            3    1145.325817   
3                     5                      2            1     631.951409   
4                     5                      2            0    1454.287831   

   shipping_fee  flat_rate  item_price  ...  buyer_group  item_region  \
0         11.75         -1       34.99  ...            3           12   
1          9.45         -1       15.50  ...            1           56   
2          0.00          0       30.00  ...            4           74   
3          0.00          0        7.00  ...            1           40   
4          0.00          0        9.74  ...            1           40   

   buyer_region  item_addr  buyer_addr  ship_id cat_id  \
0          2246          6          46        1      0   
1           924         26          24        1     20   
2          5227          1          27        1      0   
3          1413         24          13        0      9   
4          4610         24          10        0     12   

                pack_size  b2c_c2c  delivery_days  
0  PACKAGE_THICK_ENVELOPE      B2C              4  
1  PACKAGE_THICK_ENVELOPE      C2C              3  
2  PACKAGE_THICK_ENVELOPE      C2C              2  
3  PACKAGE_THICK_ENVELOPE      C2C              1  
4  PACKAGE_THICK_ENVELOPE      C2C              3  

[5 rows x 29 columns]

In [74]:
test_df = pd.read_csv(data_dir+'clean_ebay_dev.tsv.gz', sep='\t')
test_df.head()

Unnamed: 0  declared_handling_days  carrier_min_estimate  \
0           0                     3.0                     3   
1           1                     1.0                     2   
2           2                     3.0                     3   
3           3                     2.0                     2   
4           4                     1.0                     3   

   carrier_max_estimate  carrier_diff_estimate  accept_days  shipping_dist  \
0                     5                      2            2    3187.460513   
1                     5                      3            0    1303.254542   
2                     5                      2            0     585.014390   
3                     8                      6            0    1579.435253   
4                     5                      2            0     232.402677   

   shipping_fee  flat_rate  item_price  ...  buyer_group  item_region  \
0          4.50          4       10.00  ...            4           54   
1          0.00          0       62.84  ...            5           45   
2          3.95         -1        5.95  ...            9           17   
3          6.05         -1       35.00  ...            9           53   
4          0.00          0       54.80  ...            4           10   

   buyer_region  item_addr  buyer_addr  ship_id cat_id  \
0          7401         20           1        0      3   
1          9602         77           2        1      1   
2          4107         11           7        0     10   
3          8671         79          71        3     14   
4          6804         17           4        0     13   

                pack_size  b2c_c2c  delivery_days  
0  PACKAGE_THICK_ENVELOPE      B2C              4  
1  PACKAGE_THICK_ENVELOPE      B2C              5  
2  PACKAGE_THICK_ENVELOPE      C2C              2  
3                    NONE      C2C              5  
4                  LETTER      B2C              3  

[5 rows x 29 columns]

In [164]:
print(13342757 / (2*13256027))#0
print(13342757 / (2*226949))#1
#print(13342757 / (3*1408343))#2

0.5032713421600605
29.395936972623804


In [165]:
len(train_df['delivery_days'].loc[(train_df['delivery_days'] >= 8)])

226949

In [46]:
len(train_df['delivery_days'].loc[(train_df['delivery_days'] >= 1) & (train_df['delivery_days'] < 3)].values)/

6990940

In [49]:
len(train_df['delivery_days'].loc[(train_df['delivery_days'] >= 3) & (train_df['delivery_days'] < 5)].values)

4943474

In [51]:
len(train_df['delivery_days'].loc[(train_df['delivery_days'] >= 5) ].values)

1408343

In [33]:
#len(train_df['delivery_days'].loc[(train_df['delivery_days'] >= 12)].values)

In [6]:
ship_cols = pickle.load( open( data_dir+"ship_id_cols.pkl", "rb" ) )
cat_cols = pickle.load( open( data_dir+"cat_id_cols.pkl", "rb" ) )
pack_cols = pickle.load( open( data_dir+"pack_size_cols.pkl", "rb" ) )
b2c_cols = pickle.load( open( data_dir+"b2c_c2c_cols.pkl", "rb" ) )

In [7]:
def one_hot_feat(val, feat, feat_list):
    out_array = np.zeros(len(feat_list))
    val = feat+str(val)
    #print(val)
    pos = np.where(feat_list == val)[0][0]

    out_array[pos] = 1

    return pos

In [75]:
'''
train_df['ship_id'] = train_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)
train_df['pack_size'] = train_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)
train_df['cat_id'] = train_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)
train_df['b2c'] = train_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)
'''

"\ntrain_df['ship_id'] = train_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)\ntrain_df['pack_size'] = train_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)\ntrain_df['cat_id'] = train_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)\ntrain_df['b2c'] = train_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)\n"

In [104]:
samp_df = train_df.loc[(train_df['delivery_days'] >= 0) & (train_df['delivery_days'] < 8)]
samp_df

Unnamed: 0  declared_handling_days  carrier_min_estimate  \
0                  0                     1.0                     2   
1                  1                     2.0                     2   
2                  2                     3.0                     2   
3                  3                     1.0                     3   
4                  4                     1.0                     3   
...              ...                     ...                   ...   
13482971    13499995                     1.0                     2   
13482972    13499996                     1.0                     3   
13482973    13499997                     1.0                     3   
13482974    13499998                     3.0                     2   
13482975    13499999                     1.0                     3   

          carrier_max_estimate  carrier_diff_estimate  accept_days  \
0                            5                      3            0   
1                            5                      3            1   
2                            5                      3            3   
3                            5                      2            1   
4                            5                      2            0   
...                        ...                    ...          ...   
13482971                     5                      3            0   
13482972                     5                      2            0   
13482973                     5                      2            2   
13482974                     5                      3            0   
13482975                     5                      2            2   

          shipping_dist  shipping_fee  flat_rate  item_price  ...  \
0           1102.615869         11.75         -1       34.99  ...   
1            454.104441          9.45         -1       15.50  ...   
2           1145.325817          0.00          0       30.00  ...   
3            631.951409          0.00          0        7.00  ...   
4           1454.287831          0.00          0        9.74  ...   
...                 ...           ...        ...         ...  ...   
13482971     217.300247          0.00          0       97.98  ...   
13482972    1504.157567          0.00          0        5.80  ...   
13482973    1394.629319          0.00          0       12.20  ...   
13482974     292.043640          7.00          6       29.95  ...   
13482975    4153.701627          0.00          0       12.99  ...   

          buyer_group  item_region  buyer_region  item_addr  buyer_addr  \
0                   3           12          2246          6          46   
1                   1           56           924         26          24   
2                   4           74          5227          1          27   
3                   1           40          1413         24          13   
4                   1           40          4610         24          10   
...               ...          ...           ...        ...         ...   
13482971            3           52          7374          9          74   
13482972            3            8          3056         71          56   
13482973            4           17          2071         16          71   
13482974            0           72          7090          1          90   
13482975            3           40          3166         30          66   

          ship_id cat_id               pack_size  b2c_c2c  delivery_days  
0               1      0  PACKAGE_THICK_ENVELOPE      B2C              4  
1               1     20  PACKAGE_THICK_ENVELOPE      C2C              3  
2               1      0  PACKAGE_THICK_ENVELOPE      C2C              2  
3               0      9  PACKAGE_THICK_ENVELOPE      C2C              1  
4               0     12  PACKAGE_THICK_ENVELOPE      C2C              3  
...           ...    ...                     ...      ...            ...  
13482971        1     12  PACKAGE_THICK_ENVELOPE      B2C              1 

In [99]:
#samp_test_df = test_df.loc[(test_df['delivery_days'] >= 0) & (train_df['delivery_days'] < 8)]
#samp_test_df

In [105]:
samp_df['ship_id'] = samp_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)
samp_df['pack_size'] = samp_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)
samp_df['cat_id'] = samp_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)
samp_df['b2c'] = samp_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)

/var/folders/27/4vlrl2bj4dg0dw2rhjh9y88m0000gn/T/ipykernel_31145/1449736738.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  samp_df['ship_id'] = samp_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)
/var/folders/27/4vlrl2bj4dg0dw2rhjh9y88m0000gn/T/ipykernel_31145/1449736738.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  samp_df['pack_size'] = samp_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)
/var/folders/27/4vlrl2bj4dg0dw2rhjh9y88m0000gn/T/ipykernel

In [106]:
'''
samp_test_df['ship_id'] = samp_test_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)
samp_test_df['pack_size'] = samp_test_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)
samp_test_df['cat_id'] = samp_test_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)
samp_test_df['b2c'] = samp_test_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)
'''

"\nsamp_test_df['ship_id'] = samp_test_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)\nsamp_test_df['pack_size'] = samp_test_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)\nsamp_test_df['cat_id'] = samp_test_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)\nsamp_test_df['b2c'] = samp_test_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)\n"

In [52]:
scaler = pickle.load(open( data_dir+"train_minmax_scaler_3.pkl", "rb" ))
scaler

MinMaxScaler(feature_range=(-1, 1))

In [54]:
cols_num = ['declared_handling_days', 'carrier_min_estimate', 'carrier_max_estimate', 'carrier_diff_estimate', 'accept_days',  'shipping_dist', 'shipping_fee', 'flat_rate', 'item_price','quantity', 'weight', 'non_weight_rate','weight_units']


In [88]:
X = samp_df[cols_num]#samp_test_df[cols_num]
X = scaler.transform(X.values)
X

array([[-0.95      ,  0.        , -0.53846154, ..., -0.9999655 ,
        -0.75      , -1.        ],
       [-0.95      ,  0.        , -0.53846154, ..., -0.999954  ,
        -0.75      , -1.        ],
       [-0.95      , -0.33333333, -0.53846154, ..., -0.999908  ,
        -0.75      , -1.        ],
       ...,
       [-0.9       ,  0.        , -0.53846154, ..., -0.99999425,
        -1.        , -1.        ],
       [-0.95      , -0.33333333, -0.23076923, ..., -0.999908  ,
        -0.75      , -1.        ],
       [-0.85      , -0.33333333, -0.23076923, ..., -0.9999425 ,
        -0.75      , -1.        ]])

In [107]:
X = samp_df[['declared_handling_days', 'carrier_min_estimate',
       'carrier_max_estimate', 'carrier_diff_estimate', 'accept_days',
       'shipping_dist', 'shipping_fee', 'flat_rate', 'item_price', 'quantity',
       'weight', 'non_weight_rate', 'weight_units', 'payment_month',
      'item_group', 'buyer_group','seller_id', 'ship_id', 'cat_id', 'pack_size','b2c' ]].values
#y = train_df['delivery_days'].values

In [108]:
y = samp_df['delivery_days'].values
#y = samp_test_df['delivery_days'].values

In [118]:
from sklearn.ensemble import GradientBoostingRegressor

# create an xgboost regression model
reg = GradientBoostingRegressor(random_state=0, n_estimators=50, max_depth=7,subsample=0.25)


In [119]:
# create an xgboost regression model
reg.fit(X, y)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/27/4vlrl2bj4dg0dw2rhjh9y88m0000gn/T/ipykernel_31145/2898331123.py", line 2, in <module>
    reg.fit(X, y)
  File "/usr/local/lib/python3.9/site-packages/sklearn/ensemble/_gb.py", line 586, in fit
    n_stages = self._fit_stages(
  File "/usr/local/lib/python3.9/site-packages/sklearn/ensemble/_gb.py", line 663, in _fit_stages
    raw_predictions = self._fit_stage(
  File "/usr/local/lib/python3.9/site-packages/sklearn/ensemble/_gb.py", line 246, in _fit_stage
    tree.fit(X, residual, sample_weight=sample_weight, check_input=False)
  File "/usr/local/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 1315, in fit
    super().fit(
  File "/usr/local/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 420, in fit
    builder.build(self.tree_, X, y, sample_weigh

TypeError: object of type 'NoneType' has no len()

In [112]:
reg.score(X,y)

0.21915170826397168

In [113]:
x_pred = reg.predict(X)

In [114]:
from sklearn.metrics import accuracy_score
accuracy_score(np.round(x_pred),y)

0.3758284707284062

In [115]:
x_pred[:50]#[33]

array([2.72108695, 2.02968349, 2.52022445, 2.26111537, 3.0750089 ,
       3.42524774, 2.67038018, 2.7948226 , 2.52924064, 2.28287935,
       2.7490888 , 3.25214108, 2.80572797, 3.70542781, 2.33169609,
       2.58133339, 1.91112407, 3.08166793, 2.26243862, 2.59707324,
       2.54381811, 3.00660751, 2.63577246, 2.18225983, 3.16675356,
       3.21726141, 2.3801192 , 2.56190791, 3.10276137, 2.75221042,
       3.02116283, 2.61941478, 3.03415536, 3.1766373 , 2.2244481 ,
       2.70328687, 2.41939574, 2.33522331, 2.31683417, 2.46451915,
       2.66856466, 2.38199829, 2.78919367, 2.67655616, 2.40124899,
       2.83285486, 2.83749211, 2.25207211, 2.59321472, 2.02377284])

In [116]:
y[:50]#[33]

array([4, 3, 2, 1, 3, 5, 4, 4, 2, 3, 2, 2, 7, 1, 2, 4, 2, 2, 1, 4, 3, 2,
       3, 3, 2, 2, 3, 3, 6, 3, 4, 2, 2, 3, 2, 1, 4, 2, 2, 2, 4, 3, 2, 2,
       1, 3, 4, 2, 4, 2])

In [117]:
pickle.dump(reg, open( data_dir+"/class_0_bin_xgb.pkl", "wb" ))

In [90]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X, y)

KNeighborsRegressor(n_neighbors=2)

In [92]:
knn_pred = neigh.predict(X[:1000])

In [95]:
knn_pred[:40]

array([ 8. ,  9.5, 11.5,  8.5, 11.5, 10.5,  9. ,  9. , 12.5, 10.5,  9.5,
        8.5,  8. ,  8. , 17.5,  8.5,  8. , 11. , 13. , 11. , 11.5,  8.5,
        8. ,  8.5,  8. ,  8. ,  8.5,  8. ,  8.5,  9. ,  8. ,  9.5, 10.5,
       24.5, 14. ,  9.5,  8.5, 10.5, 10. , 21. ])

In [96]:
y[:40]

array([ 8,  9, 14,  9, 13, 11, 10,  8, 14,  8, 11,  9,  8,  8, 27,  9,  8,
       14, 17, 10, 10,  8,  8,  9,  8,  8,  9,  8,  8,  8,  8,  9, 10, 36,
       17,  9,  8, 11, 11, 27])

In [86]:
accuracy_score(np.round(knn_pred),y)

0.25419192316775563

In [87]:
print(precision_recall_fscore_support(np.round(knn_pred),y))

(array([0.42768755, 0.22426192, 0.14383971, 0.09411173, 0.06202209,
       0.0591716 , 0.03975535, 0.02005013, 0.02222222, 0.        ,
       0.01796407, 0.02919708, 0.02409639, 0.02061856, 0.05357143,
       0.        , 0.        , 0.02777778, 0.03125   , 0.        ,
       0.        , 0.        , 0.07692308, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.1       , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ]), array([0.42436451, 0.22178551, 0.14234981, 0.09415911, 0.06191688,
       0.06451613, 0.03981623, 0.02259887, 0.02362205, 0.        ,
       0.02142857, 0.03478261, 0.01886792, 0.02105263, 0.05263158,
       0.        , 0.        , 0.03571429, 0.03571429, 0.        ,
       0.        , 0.       

/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [91]:
pickle.dump(neigh, open( data_dir+"/class_1_bin_knn.pkl", "wb" ))

In [68]:
y[:100]

array([4, 3, 2, 1, 3, 5, 4, 4, 2, 3, 2, 2, 7, 1, 2, 4, 2, 2, 1, 4, 3, 2,
       3, 3, 2, 2, 3, 3, 6, 3, 8, 4, 2, 2, 3, 2, 1, 4, 2, 2, 2, 4, 3, 2,
       2, 1, 3, 4, 2, 4, 2, 3, 5, 1, 6, 2, 3, 5, 3, 3, 5, 1, 7, 3, 9, 3,
       5, 2, 2, 4, 2, 4, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 4, 4, 3, 3, 2, 2,
       2, 2, 3, 5, 4, 2, 2, 2, 5, 1, 1, 2])

In [69]:
np.mean(y)

2.7558826033659036

In [62]:
x_pred[:100]

array([2.76394503, 2.18974395, 2.67944877, 2.28954298, 2.91781611,
       3.29313438, 2.77522849, 2.80216127, 2.69158304, 2.40418882,
       2.8118265 , 3.75548204, 2.79974352, 4.42450155, 2.30726652,
       2.63872337, 2.04433665, 2.95832309, 2.43800815, 2.65498503,
       2.63872337, 2.91535805, 2.66583346, 2.49974921, 2.81306605,
       3.97703437, 2.63872337, 2.60734876, 3.41373427, 2.76023835,
       2.20858274, 2.91781611, 2.75417202, 3.84758044, 3.21216687,
       2.30105176, 2.74691581, 2.6495718 , 2.40418882, 2.32978318,
       2.58283373, 2.54638938, 2.51601087, 2.79974352, 2.75417202,
       2.63872337, 2.80459833, 2.86232417, 2.38147377, 2.78173038,
       2.17034586, 4.86542996, 4.94063824, 2.19937742, 4.84042657,
       2.51601087, 2.60794165, 4.95396077, 2.99228825, 2.81306605,
       2.65498503, 2.991398  , 3.13011827, 2.67483739, 3.23927696,
       2.89675964, 2.56705898, 2.97937956, 2.56177727, 2.92388763,
       2.77522849, 2.51470334, 2.7869848 , 2.62873425, 4.64240

NameError: name 'np' is not defined

In [80]:
import torch
ebay_loss(torch.Tensor(x_pred), torch.Tensor(y))

tensor(1.4206)

In [17]:
dev_df = pd.read_csv(data_dir+'clean_ebay_dev.tsv.gz', sep='\t')
dev_df.head()

/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (17,19,20,21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Unnamed: 0  declared_handling_days  carrier_min_estimate  \
0           0                     3.0                     3   
1           1                     1.0                     2   
2           2                     3.0                     3   
3           3                     2.0                     2   
4           4                     1.0                     3   

   carrier_max_estimate  carrier_diff_estimate  accept_days  shipping_dist  \
0                     5                      2            2    3187.460513   
1                     5                      3            0    1303.254542   
2                     5                      2            0     585.014390   
3                     8                      6            0    1579.435253   
4                     5                      2            0     232.402677   

   shipping_fee  flat_rate  item_price  ...  buyer_group  item_region  \
0          4.50          4       10.00  ...            4           54   
1          0.00          0       62.84  ...            5           45   
2          3.95         -1        5.95  ...            9           17   
3          6.05         -1       35.00  ...            9           53   
4          0.00          0       54.80  ...            4           10   

   buyer_region  item_addr  buyer_addr  ship_id cat_id  \
0            74         20         1.0        0      3   
1            96         77         2.0        1      1   
2            41         11         7.0        0     10   
3            86         79        71.0        3     14   
4            68         17         4.0        0     13   

                pack_size b2c_c2c delivery_days  
0  PACKAGE_THICK_ENVELOPE     B2C             4  
1  PACKAGE_THICK_ENVELOPE     B2C             5  
2  PACKAGE_THICK_ENVELOPE     C2C             2  
3                    NONE     C2C             5  
4                  LETTER     B2C             3  

[5 rows x 27 columns]

In [20]:
dev_df['ship_id'] = dev_df['ship_id'].apply(one_hot_feat,feat='ship_id_',feat_list=ship_cols)
dev_df['pack_size'] = dev_df['pack_size'].apply(one_hot_feat,feat='pack_size_',feat_list=pack_cols)
dev_df['cat_id'] = dev_df['cat_id'].apply(one_hot_feat,feat='cat_id_',feat_list=cat_cols)
dev_df['b2c_c2c'] = dev_df['b2c_c2c'].apply(one_hot_feat,feat='b2c_c2c_',feat_list=b2c_cols)

In [34]:
x_cols = ['declared_handling_days', 'carrier_min_estimate',
       'carrier_max_estimate', 'carrier_diff_estimate', 'accept_days',
       'shipping_dist', 'shipping_fee', 'flat_rate', 'item_price', 'quantity',
       'weight', 'non_weight_rate', 'weight_units', 'payment_month',
      'item_group', 'buyer_group','seller_id', 'ship_id', 'cat_id', 'pack_size','b2c' ]

In [35]:
feat_imp = reg.feature_importances_

In [36]:
feat_imp

array([1.39490468e-02, 4.03727443e-03, 1.24132633e-01, 1.72612456e-01,
       3.50654868e-01, 1.83974882e-01, 1.40640450e-04, 0.00000000e+00,
       2.30580777e-03, 5.23329450e-04, 5.11835150e-04, 0.00000000e+00,
       0.00000000e+00, 6.21845727e-02, 9.92371841e-03, 6.17478259e-03,
       3.62907201e-02, 1.24404988e-02, 2.15276818e-03, 1.79898386e-02,
       3.27458685e-07])

In [49]:
count = 0
for x in feat_imp:
    print(count,":",x)
    count += 1

0 : 0.013949046827319409
1 : 0.004037274433382638
2 : 0.12413263299036215
3 : 0.17261245641477851
4 : 0.3506548676913515
5 : 0.18397488189646627
6 : 0.00014064045030554614
7 : 0.0
8 : 0.0023058077672135817
9 : 0.0005233294495260637
10 : 0.0005118351497962698
11 : 0.0
12 : 0.0
13 : 0.06218457273022998
14 : 0.009923718406729369
15 : 0.006174782586274598
16 : 0.03629072011545744
17 : 0.012440498842286004
18 : 0.0021527681769415935
19 : 0.017989838612894132
20 : 3.274586852935758e-07


In [38]:
print(x_cols[2])
print(x_cols[3])
print(x_cols[4])
print(x_cols[5])

carrier_max_estimate
carrier_diff_estimate
accept_days
shipping_dist


In [39]:
print(x_cols[0])
print(x_cols[13])
print(x_cols[16])
print(x_cols[17])
print(x_cols[19])

declared_handling_days
payment_month
seller_id
ship_id
pack_size


In [41]:
print(x_cols[1])
print(x_cols[8])
print(x_cols[14])
print(x_cols[15])
print(x_cols[18])

carrier_min_estimate
item_price
item_group
buyer_group
cat_id


In [40]:
#add nothing
print(x_cols[7])
print(x_cols[11])
print(x_cols[12])
print(x_cols[20])

flat_rate
non_weight_rate
weight_units
b2c


In [20]:
x_cols = ['declared_handling_days', 'carrier_min_estimate',
       'carrier_max_estimate', 'carrier_diff_estimate', 'accept_days',
       'shipping_dist', 'shipping_fee', 'flat_rate', 'item_price', 'quantity',
       'weight', 'non_weight_rate', 'weight_units', 'payment_month',
      'item_group', 'buyer_group','seller_id', 'ship_id', 'cat_id', 'pack_size','b2c' ]

In [38]:
print(x_cols[3])
print(x_cols[4])
print(x_cols[5])

carrier_diff_estimate
accept_days
shipping_dist


In [40]:
print(x_cols[2])
print(x_cols[13])
print(x_cols[14])

carrier_max_estimate
payment_month
seller_id


In [41]:
print(x_cols[0])
print(x_cols[15])
print(x_cols[17])

declared_handling_days
ship_id
pack_size


In [4]:
# no importance
print(x_cols[7])
print(x_cols[9])
print(x_cols[11])
print(x_cols[12])


flat_rate
quantity
non_weight_rate
weight_units
